# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46bd8657cfe40193bc03cb724247cde8282d4761774e5c97dac620976549c31078c6e7e6000a2b5a77f58310745e5435d52e820773c3387092afe8bcdea24587

test:
  secret_key_base: e3d483cd539218d3f994c2a6cc6e0429f9f430609ff39fe44eb7d6a34ee11a1c1e609dc305e4615913a708125eddbd3eb8fd8de52ca18499db69c1c01231e536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
